filter_ground:
  ros__parameters:
    input_topic: "/rslidar_points"
    output_topic: "/rslidar_points_filtered"
    scan_topic: "/rslidar_points_filtered_scan"

    azimuth_fov_deg: 100.0
    ransac_iterations: 90
    distance_threshold: 0.05
    cell_size: 0.25
    use_ransac_filter: true

    max_slope_deg: 35.0
    slope_ring_width: 0.10

    scan_angle_increment_deg: 0.5
    scan_range_min: 0.05
    scan_range_max: 100.0

    bag_play_enabled: false
    bag_file: ""
    bag_loop: true
